export const FlagshipEvents = [
  {
    club: ``,
    rulebook: `https://www.drive.com`,
    name: `Opening Ceremony`,
    description: `A grand cultural inauguration featuring traditional performances, lights, and a spectacular welcome.`,
    posterurl: `https://res.cloudinary.com/dz4lwydkp/image/upload/v1767560704/nitrutsav-2026/e3f3vljzfvu8d5g4zwxx.webp`,
  },
  {
    club: ``,
    rulebook: `https://www.drive.com`,
    name: `Battle of Bands`,
    description: `College bands compete with electrifying performances to win hearts and glory.`,
    posterurl: `https://res.cloudinary.com/dz4lwydkp/image/upload/v1767560704/nitrutsav-2026/e3f3vljzfvu8d5g4zwxx.webp`,
  },
  {
    club: ``,
    rulebook: `https://www.drive.com`,
    name: `EDM Night`,
    description: `A high-energy electronic music night with powerful beats, lights, and crowd-pumping vibes.`,
    posterurl: `https://res.cloudinary.com/dz4lwydkp/image/upload/v1767560704/nitrutsav-2026/e3f3vljzfvu8d5g4zwxx.webp`,
  },
  {
    club: ``,
    rulebook: `https://www.drive.com`,
    name: `Classical Night`,
    description: `An enchanting evening of Indian classical music and dance celebrating timeless art forms.`,
    posterurl: `https://res.cloudinary.com/dz4lwydkp/image/upload/v1767560704/nitrutsav-2026/e3f3vljzfvu8d5g4zwxx.webp`,
  },
  {
    club: ``,
    rulebook: `https://www.drive.com`,
    name: `Fashion Show`,
    description: `A glamorous showcase of creativity, style, and storytelling through fashion.`,
    posterurl: `https://res.cloudinary.com/dz4lwydkp/image/upload/v1767560704/nitrutsav-2026/e3f3vljzfvu8d5g4zwxx.webp`,
  },
  {
    club: ``,
    rulebook: `https://www.drive.com`,
    name: `Dance Night`,
    description: `An explosive night featuring group and solo dance performances across multiple styles.`,
    posterurl: `https://res.cloudinary.com/dz4lwydkp/image/upload/v1767560704/nitrutsav-2026/e3f3vljzfvu8d5g4zwxx.webp`,
  },
  {
    club: ``,
    rulebook: `https://www.drive.com`,
    name: `Drama & Theatre`,
    description: `Powerful stage plays and theatrical performances conveying stories with emotion and depth.`,
    posterurl: `https://res.cloudinary.com/dz4lwydkp/image/upload/v1767560704/nitrutsav-2026/e3f3vljzfvu8d5g4zwxx.webp`,
  },
  {
    club: ``,
    rulebook: `https://www.drive.com`,
    name: `Celebrity Night`,
    description: `A star-studded evening featuring a renowned artist performing live on stage.`,
    posterurl: `https://res.cloudinary.com/dz4lwydkp/image/upload/v1767560704/nitrutsav-2026/e3f3vljzfvu8d5g4zwxx.webp`,
  },
  {
    club: ``,
    rulebook: `https://www.drive.com`,
    name: `Cultural Parade`,
    description: `A vibrant parade showcasing diverse cultures, traditions, and artistic expressions.`,
    posterurl: `https://res.cloudinary.com/dz4lwydkp/image/upload/v1767560704/nitrutsav-2026/e3f3vljzfvu8d5g4zwxx.webp`,
  },
  {
    club: ``,
    rulebook: `https://www.drive.com`,
    name: `Closing Ceremony`,
    description: `The grand finale celebrating achievements, memories, and the spirit of the cultural fest.`,
    posterurl: `https://res.cloudinary.com/dz4lwydkp/image/upload/v1767560704/nitrutsav-2026/e3f3vljzfvu8d5g4zwxx.webp`,
  },
];
