export const FunEvents = [
  {
    club: ``,
    rulebook: `https://www.drive.com`,
    name: `Treasure Hunt`,
    description: `Race across campus solving clues and completing challenges to uncover the final treasure.`,
    posterurl: `https://res.cloudinary.com/dz4lwydkp/image/upload/v1767560704/nitrutsav-2026/e3f3vljzfvu8d5g4zwxx.webp`,
  },
  {
    club: ``,
    rulebook: `https://www.drive.com`,
    name: `Open Mic Night`,
    description: `A free stage for poetry, music, comedy, and spontaneous performances.`,
    posterurl: `https://res.cloudinary.com/dz4lwydkp/image/upload/v1767560704/nitrutsav-2026/e3f3vljzfvu8d5g4zwxx.webp`,
  },
  {
    club: ``,
    rulebook: `https://www.drive.com`,
    name: `Gaming Arena`,
    description: `Compete in popular PC and console games with friends and rivals.`,
    posterurl: `https://res.cloudinary.com/dz4lwydkp/image/upload/v1767560704/nitrutsav-2026/e3f3vljzfvu8d5g4zwxx.webp`,
  },
  {
    club: ``,
    rulebook: `https://www.drive.com`,
    name: `Minute to Win It`,
    description: `Fast-paced mini games that test your speed, focus, and coordination.`,
    posterurl: `https://res.cloudinary.com/dz4lwydkp/image/upload/v1767560704/nitrutsav-2026/e3f3vljzfvu8d5g4zwxx.webp`,
  },
  {
    club: ``,
    rulebook: `https://www.drive.com`,
    name: `Spin the Wheel`,
    description: `Try your luck with exciting dares, tasks, and surprise rewards.`,
    posterurl: `https://res.cloudinary.com/dz4lwydkp/image/upload/v1767560704/nitrutsav-2026/e3f3vljzfvu8d5g4zwxx.webp`,
  },
  {
    club: ``,
    rulebook: `https://www.drive.com`,
    name: `Dumb Charades`,
    description: `Guess the movie, song, or phrase through hilarious actions and gestures.`,
    posterurl: `https://res.cloudinary.com/dz4lwydkp/image/upload/v1767560704/nitrutsav-2026/e3f3vljzfvu8d5g4zwxx.webp`,
  },
  {
    club: ``,
    rulebook: `https://www.drive.com`,
    name: `Quizathon`,
    description: `A fun and interactive quiz covering pop culture, movies, music, and memes.`,
    posterurl: `https://res.cloudinary.com/dz4lwydkp/image/upload/v1767560704/nitrutsav-2026/e3f3vljzfvu8d5g4zwxx.webp`,
  },
  {
    club: ``,
    rulebook: `https://www.drive.com`,
    name: `Bollywood Bingo`,
    description: `A desi twist on bingo with Bollywood songs, dialogues, and moments.`,
    posterurl: `https://res.cloudinary.com/dz4lwydkp/image/upload/v1767560704/nitrutsav-2026/e3f3vljzfvu8d5g4zwxx.webp`,
  },
  {
    club: ``,
    rulebook: `https://www.drive.com`,
    name: `Photo Booth Carnival`,
    description: `Capture memories with themed photo booths, props, and instant prints.`,
    posterurl: `https://res.cloudinary.com/dz4lwydkp/image/upload/v1767560704/nitrutsav-2026/e3f3vljzfvu8d5g4zwxx.webp`,
  },
  {
    club: ``,
    rulebook: `https://www.drive.com`,
    name: `Street Games Zone`,
    description: `Relive childhood fun with games like gitte, kanche, and lagori.`,
    posterurl: `https://res.cloudinary.com/dz4lwydkp/image/upload/v1767560704/nitrutsav-2026/e3f3vljzfvu8d5g4zwxx.webp`,
  },
];
