export const ProShows = [
  {
    club: ``,
    rulebook: ``,
    name: `Olly Esse`,
    description: `DJ Night Headliner`,
    posterurl: `https://res.cloudinary.com/dz4lwydkp/image/upload/v1769527792/nitrutsav-2026/krwjrjnhkdllc6s6pekq.jpg`,
  },
  {
    club: `HeartBeats`,
    rulebook: `https://drive.google.com/open?id=1MW7JKs6P3QLbeyG16vx1MrIc0aEUvlWA`,
    name: `Maktub`,
    description: `Join us for a magical evening of music under the stars.`,
    posterurl: `https://res.cloudinary.com/domaovjhf/image/upload/v1769110699/nitrutsav-2026/eifnbyggqqvs6agqpbxf.webp`,
  },
  {
    club: ``,
    rulebook: ``,
    name: `Coming Soon`,
    description: `Coming soon`,
    posterurl: `https://res.cloudinary.com/domaovjhf/image/upload/v1767961282/nitrutsav-2026/e3f3vljzfvu8d5g4zwxx.webp`,
  },
  {
    club: ``,
    rulebook: ``,
    name: `Coming Soon`,
    description: `Coming soon`,
    posterurl: `https://res.cloudinary.com/domaovjhf/image/upload/v1767961282/nitrutsav-2026/e3f3vljzfvu8d5g4zwxx.webp`,
  },
  {
    club: ``,
    rulebook: ``,
    name: `Coming Soon`,
    description: `Coming soon`,
    posterurl: `https://res.cloudinary.com/domaovjhf/image/upload/v1767961282/nitrutsav-2026/e3f3vljzfvu8d5g4zwxx.webp`,
  },
  {
    club: ``,
    rulebook: ``,
    name: `Coming Soon`,
    description: `Coming soon`,
    posterurl: `https://res.cloudinary.com/domaovjhf/image/upload/v1767961282/nitrutsav-2026/e3f3vljzfvu8d5g4zwxx.webp`,
  },
  {
    club: ``,
    rulebook: ``,
    name: `Coming Soon`,
    description: `Coming soon`,
    posterurl: `https://res.cloudinary.com/domaovjhf/image/upload/v1767961282/nitrutsav-2026/e3f3vljzfvu8d5g4zwxx.webp`,
  },
  {
    club: ``,
    rulebook: ``,
    name: `Coming Soon`,
    description: `Coming soon`,
    posterurl: `https://res.cloudinary.com/domaovjhf/image/upload/v1767961282/nitrutsav-2026/e3f3vljzfvu8d5g4zwxx.webp`,
  },
  {
    club: ``,
    rulebook: ``,
    name: `Coming Soon`,
    description: `Coming soon`,
    posterurl: `https://res.cloudinary.com/domaovjhf/image/upload/v1767961282/nitrutsav-2026/e3f3vljzfvu8d5g4zwxx.webp`,
  },
  {
    club: ``,
    rulebook: ``,
    name: `Coming Soon`,
    description: `Coming soon`,
    posterurl: `https://res.cloudinary.com/domaovjhf/image/upload/v1767961282/nitrutsav-2026/e3f3vljzfvu8d5g4zwxx.webp`,
  },
  {
    club: ``,
    rulebook: ``,
    name: `Coming Soon`,
    description: `Coming soon`,
    posterurl: `https://res.cloudinary.com/domaovjhf/image/upload/v1767961282/nitrutsav-2026/e3f3vljzfvu8d5g4zwxx.webp`,
  },
  {
    club: ``,
    rulebook: ``,
    name: `Coming Soon`,
    description: `Coming soon`,
    posterurl: `https://res.cloudinary.com/domaovjhf/image/upload/v1767961282/nitrutsav-2026/e3f3vljzfvu8d5g4zwxx.webp`,
  },
];
