export const WorkshopandExihibition = [
  {
    club: ``,
    rulebook: ``,
    name: `Coming Soon`,
    description: `Coming soon`,
    posterurl: `https://res.cloudinary.com/domaovjhf/image/upload/v1767961282/nitrutsav-2026/e3f3vljzfvu8d5g4zwxx.webp`,
  },
  {
    club: ``,
    rulebook: ``,
    name: `Coming Soon`,
    description: `Coming soon`,
    posterurl: `https://res.cloudinary.com/domaovjhf/image/upload/v1767961282/nitrutsav-2026/e3f3vljzfvu8d5g4zwxx.webp`,
  },
  {
    club: ``,
    rulebook: ``,
    name: `Coming Soon`,
    description: `Coming soon`,
    posterurl: `https://res.cloudinary.com/domaovjhf/image/upload/v1767961282/nitrutsav-2026/e3f3vljzfvu8d5g4zwxx.webp`,
  },
  {
    club: ``,
    rulebook: ``,
    name: `Coming Soon`,
    description: `Coming soon`,
    posterurl: `https://res.cloudinary.com/domaovjhf/image/upload/v1767961282/nitrutsav-2026/e3f3vljzfvu8d5g4zwxx.webp`,
  },
  {
    club: ``,
    rulebook: ``,
    name: `Coming Soon`,
    description: `Coming soon`,
    posterurl: `https://res.cloudinary.com/domaovjhf/image/upload/v1767961282/nitrutsav-2026/e3f3vljzfvu8d5g4zwxx.webp`,
  },
  {
    club: ``,
    rulebook: ``,
    name: `Coming Soon`,
    description: `Coming soon`,
    posterurl: `https://res.cloudinary.com/domaovjhf/image/upload/v1767961282/nitrutsav-2026/e3f3vljzfvu8d5g4zwxx.webp`,
  },
  {
    club: ``,
    rulebook: ``,
    name: `Coming Soon`,
    description: `Coming soon`,
    posterurl: `https://res.cloudinary.com/domaovjhf/image/upload/v1767961282/nitrutsav-2026/e3f3vljzfvu8d5g4zwxx.webp`,
  },
  {
    club: ``,
    rulebook: ``,
    name: `Coming Soon`,
    description: `Coming soon`,
    posterurl: `https://res.cloudinary.com/domaovjhf/image/upload/v1767961282/nitrutsav-2026/e3f3vljzfvu8d5g4zwxx.webp`,
  },
  {
    club: ``,
    rulebook: ``,
    name: `Coming Soon`,
    description: `Coming soon`,
    posterurl: `https://res.cloudinary.com/domaovjhf/image/upload/v1767961282/nitrutsav-2026/e3f3vljzfvu8d5g4zwxx.webp`,
  },
  {
    club: ``,
    rulebook: ``,
    name: `Coming Soon`,
    description: `Coming soon`,
    posterurl: `https://res.cloudinary.com/domaovjhf/image/upload/v1767961282/nitrutsav-2026/e3f3vljzfvu8d5g4zwxx.webp`,
  },
];
